### PR TITLE
Torch support

### LINKED ISSUE #42: Add Torch support
Currently we support Tensorflow or manually adding weigths from other frameworks. 

Torch support to easily use the nn2poly should be added.

### PR DESCRIPTION
**Pull request by nachodieez**
This PR adds torch support and closes #42.

The main contributions of this PR are the following ones:

- Created some new functions to make the package compatible with torch. They can be found in the file `torch_helpers.R`
- New `get_model_parameters` method for objects of class `nn_module`.
- New `nn2poly` method for objects of class `nn_module`.
- The `add_constraints` function is now a generic. However, this function can not be used with torch `nn_module`.
- Tests for the new functions.
- Added `luz` and `torch` to suggests.

The constrained training for torch models can be done using the luz API and customizing the training process using the `luz_constraint` function as a callback. L1 and L2 constrained training are currently available and the type of the constraint can be selected changing the `constraint_type` parameter of the `luz_constraint` function. The default value is l1.

Also, now torch is installed in GitHub Actions and apple silicon processors are tested.

### CODE REVIEW

**Comment by Enchufa2** [comment]
@moralapablo Let me take a look before merging to see if I can think of a way of integrating this into the existing workflow.

**Comment by Enchufa2** [comment]
I've introduced some more changes. The previous torch parser was problematic, because it relied on a specific way of building the `nn_module`. Unfortunately, it seems that there's no general way of knowing how the layers are connected, so I think that the best approach is to force a workflow. With the latest commits, we require a sequential NN, and an error ir raised if this is not met, pointing to the new `luz_model_sequential`. The new workflow, now similar to keras, is

```r
library(nn2poly)
library(luz)

# only works with this helper
nn <- luz_model_sequential(
  torch::nn_linear(2,2),
  torch::nn_softplus(),
  torch::nn_linear(2,3),
  torch::nn_softplus(),
  torch::nn_linear(3,1)
)

# same as before
fitted <- nn |>
  setup(...) |>
  add_constraints() |>
  fit(...)
```

By forcing a sequential NN, we ensure that the resulting object has its `children` in the proper order, and therefore info can be extracted trivially.

**Comment by Enchufa2** [comment]
Fixed the couple of issues we saw yesterday.

**Review by moralapablo — APPROVED** [review]

**Comment by moralapablo** [comment]
With the final addition of a complete case in the torch regression vignette, which works perfectly fine, we are ready to merge

**Pull request merged**
